/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sonalake.shotgun;

import com.sonalake.shotgun.usage.ShotgunConfig;
import freemarker.template.TemplateException;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Paths;

class AppTest {
    @Test
    void appHasAGreeting() throws GitAPIException, IOException, TemplateException {
        App classUnderTest = new App();
        classUnderTest.process(ShotgunConfig.builder()
                .inputDirectory(Paths.get("/home/daniel/workspaces/enet/billing-validation"))
                .outputFile(Paths.get(".shotgun/report.html"))
                .sourceSet("src/main/java")
                .sourceSet("src/main/resources")
                .sourceSet("src/main/webapp")
                .sourceSet("src/test/java")
                .sourceSet("src/test/resources")
                .minimumCommitInterest(3)
                .topCommitValueForFileSets(10)
                .topCommitValueForFiles(40)
                .legendLevel(10)
                .legendLevel(20)
                .legendLevel(30)
                .legendLevel(50)
                .legendLevel(80)
                .legendLevel(120)
                .build());
    }
}
